<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $page = $this->getPage() ?>

<?php

#$parent = $page->getParentPage();
#$root = $page->getRootPage();

?>

<?php #if ($parent): ?>
	<?php #echo $parent->getPostTitle() ?>
	<?php #echo $parent->hasChildren() ?>
<?php #endif; ?>	

<?php #if ($root): ?>
	<?php #echo $root->getPostTitle() ?>
	<?php #echo $root->hasChildren() ?>
<?php #endif; ?>	

<?php if ($page): ?>
	<?php $helper = $this->helper('wordpress') ?>
	<?php $author = $page->getAuthor() ?>

	<?php
	// remove page-links UL element from content to display where we choose
	$content = $page->getPostContent();
	$links = "";
	$pattern = '#\<ul id="page-links"\>(.+?)\<\/ul\>#s';
	preg_match($pattern, $content, $matches);
	if (count($matches) > 0) {
		$links = $matches[0];
		$content = preg_replace($pattern, "", $content);
	}
	?>


	<div class="page-title">
		<h1><?php echo $page->getPostTitle() ?></h1>
		<?php echo $links ?>
	</div>
	<div class="post-view">
		<div class="entry std">
			<?php if ($page->isViewableForVisitor()): ?>
				<?php if ($featuredImage = $page->getFeaturedImage()): ?>
					<div class="featured-image left"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt=""/></div>
				<?php endif; ?>
				<?php echo $content ?>
				<br style="clear:both;"/>
			<?php else: ?>
				<?php echo $this->getPasswordProtectHtml() ?>
			<?php endif; ?>
		</div>
		<?php echo $this->getCommentsHtml() ?>
	</div>
<?php endif; ?>
